services:
  my-nextapp:
    build:
      dockerfile: Dockerfile
    image: booking-meeting-room/my-nextapp:latest
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=tai.vnpsc.com,www.tai.vnpsc.com
      - LETSENCRYPT_HOST=tai.vnpsc.com,www.tai.vnpsc.com
      - LETSENCRYPT_EMAIL=spinatp@gmail.com  # email to encrypt information
    ports:
      - "3000:3000"   # optional
    networks:
      shared:
        aliases:
          - my-nextapp
    restart: always
networks:
  shared:
    external: true
    name: my_tailt_shared_net