name: "Local-Build and deploy booking meeting room to server"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tags docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/booking-meeting-room-app # Change this to your docker image name

      - name: Create .env file # Tạo File .env
        run: |
          echo "JINA=${{ secrets.JINA }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: Build and push to docker hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: taile0/booking-meeting-room-app:latest
          secrets: |
            "DATABASE_URL=${{ secrets.DATABASE_URL }}"
            "JINA=${{ secrets.JINA }}"

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_LOCAL }} # Địa chỉ của server
          username: ${{ secrets.USERNAME_LOCAL }} # Username để login vào server
          key: ${{ secrets.SSH_KEY_LOCAL }} # Private key để login vào server

          script: |
            docker pull taile0/booking-meeting-room-app:latest
            docker stop next-booking-meeting-room-app || true
            docker rm next-booking-meeting-room-app || true
            docker images -a |  grep "taile0/booking-meeting-room-app" | awk '{print $3}' | xargs docker rmi
            docker run -d --name next-booking-meeting-room-app -p 127.0.0.1:3000:3000 taile0/booking-meeting-room-app:latest
